package.json

enhancement
___
- Simplified the build script in `package.json` by removing the TypeScript compilation step (`tsc -b`).
___
<tr>
<td>
<details>
<summary><strong>package.json</strong><dd><code>Simplify build script by removing TypeScript compilation.</code></dd></summary>
<hr>
package.json
- Removed TypeScript compilation step from the build script.
</details>
</td>
<td><a href="https://github.com/UCTalent/uc-ats-react-app/pull/20/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519">+1/-1</a>&nbsp; &nbsp; &nbsp; </td>
</tr>                    
</table></td></tr></tr></tbody></table>
___
> 💡 **PR-Agent usage**:
>Comment `/help` on …

Simplify Vite build script in package.json

---

package.json
src/assets/css/dnd.module.css
src/components/common/dnd/DndContainer.tsx
src/components/common/dnd/DndDraggable.tsx
src/components/common/dnd/index.ts
src/components/sections/job-detail/CandidateStageColumn.tsx
src/components/sections/job-detail/TitleOverview.tsx
src/hooks/useDndKanbanBoard.ts
src/hooks/useHook.ts
src/layouts/JobDetailLayout.tsx
src/pages/TheJobDetailPage.tsx
src/services/dnd/applyDrag.ts
src/services/dnd/index.ts
src/types/dnd.ts
src/utils/bindClass.ts
src/utils/mockDndScene.ts
yarn.lock

Enhancement, Other
___
- Added `DndContainer` and `DndDraggable` components for drag-and-drop functionality.
- Created `useDndKanbanBoard` hook for managing Kanban board state.
- Integrated drag-and-drop functionality in `TheJobDetailPage`.
- Defined types for drag-and-drop scene and card props.
- Added `applyDrag` function to handle drag-and-drop logic.
- Created mock data for drag-and-drop scene.
- Added `react-smooth-dnd` dependency.
- Updated `CandidateStageColumn` to accept children as props.
- Refactored `TitleOverview` component for key prop and padding.
- Removed unused `useHooks` file.
- Removed unnecessary padding from `JobDetailLayout`.
- Added CSS classes for drag-and-drop previews.
___
<table><thead><tr><th></th><th align="left">Relevant …

Integrate drag-and-drop functionality using react-smooth-dnd

---

src/components/common/menus/MenuBasic.tsx
src/components/common/menus/index.ts
src/components/common/tags/BeautifulColorTag.tsx
src/components/sections/job-detail/TabMenuHorizontal.tsx
src/components/subsections/job-detail/CandidateStageColumnCard.tsx

Enhancement, Bug fix
___
- Added a new `MenuBasic` component for handling menus with MUI.
- Exported `MenuBasic` and `IMenuItem` from the menus index file.
- Fixed typos in SVG attributes in `BeautifulColorTag`.
- Enhanced `TabMenuHorizontal` by adding a `disabled` property to menu items and adjusting styles.
- Integrated `MenuBasic` in `CandidateStageColumnCard` for candidate actions.
___
<tr>
<td>
<details>
<summary><strong>MenuBasic.tsx</strong><dd><code>Add new `MenuBasic` component with menu handling.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/common/menus/MenuBasic.tsx
<li>Created a new …

Add `MenuBasic` Component and Enhance Menu Handling in Job Detail Page

---

src/assets/css/dnd.module.css
src/components/common/dnd/DndContainer.tsx
src/components/common/dnd/DndDraggable.tsx
src/components/common/user-avatar/UserAvatar.tsx
src/components/sections/job-detail/CandidateStageColumn.tsx
src/components/subsections/job-detail/CandidateStageColumnCard.tsx
src/hooks/useDndKanbanBoard.ts
src/pages/TheJobCandidatePage.tsx

Enhancement, Bug fix
___
- Optimized multiple components (`DndContainer`, `DndDraggable`, `CandidateStageColumn`, `CandidateStageColumnCard`) using `memo` for better performance.
- Enhanced `UserAvatar` component styles to improve user experience.
- Added new state management and callbacks in `useDndKanbanBoard` hook to handle drag-and-drop events more effectively.
- Refactored `TheJobCandidatePage` to remove unused drag event handlers and update `DndContainer` props.
- Updated CSS styles for drag-and-drop elements.
___
<tr>
<td>
<details>
<summary><strong>DndContainer.tsx</strong><dd><code>Optimize DndContainer with memo and new prop</code>&nbsp; &nbsp; …

Enhance drag-and-drop components and optimize rendering performance

---

package.json
src/assets/css/quill.module.scss
src/components/common/ModalWithHeader.tsx
src/components/common/WrapperSEO.tsx
src/components/common/WrapperSectionContent.tsx
src/components/common/form-fields/AutocompleteField.tsx
src/components/common/form-fields/RichTextEditor.tsx
src/components/common/form-fields/SelectField.tsx
src/components/sections/job-detail/JobDetailContent.tsx
src/components/sections/job-detail/TabMenuHorizontal.tsx
src/hooks/useClickOutside.ts
src/pages/TheJobNotePage.tsx
src/routes/RouteElement.tsx
yarn.lock

Enhancement, Bug fix, Other
___
- Enhanced `RichTextEditor` with new styles, focus and blur handlers, and integrated `useClickOutside` hook.
- Renamed several components for consistency (`WrappedSEO` to `WrapperSEO`, `WrapperSection` to `WrapperSectionContent`).
- Fixed import statements in multiple components.
- Enabled the "Notes" tab in `TabMenuHorizontal`.
- Added `RichTextEditor` to `TheJobNotePage`.
- Added `sass` dependency.
___
</strong></td><td><details><summary>3 files</summary><table>
<tr>
<td>
<details>
<summary><strong>ModalWithHeader.tsx</strong><dd><code>Fix import statement for `IconClose` icon.</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; …

Enhance RichTextEditor and Rename Components for Consistency

---

src/App.tsx
src/components/common/PopConfirm.tsx
src/components/common/buttons/ButtonOutlined.tsx
src/hooks/atoms/useConfirmAtom.ts
src/hooks/useDndKanbanBoard.ts
src/layouts/JobCandidateInfoLayout.tsx
src/providers/PopConfirmProvider.tsx
src/store/confirmAtom.ts
src/types/dnd.ts
src/types/store/confirm.ts

Enhancement, Tests
___
- Added `PopConfirmProvider` to the application providers.
- Created `PopConfirm` component for confirmation modals.
- Added support for `sx` prop in `ButtonOutlined` component.
- Created `useConfirmAtom` hook for managing confirmation state.
- Integrated confirmation modal for drag-and-drop actions in Kanban board.
- Enhanced drag-and-drop logic to handle multiple columns.
- Added box shadow to `JobCandidateInfoLayout` stack.
- Created `PopConfirmProvider` component.
- Created Recoil atom `confirmAtom` for confirmation state.
- Added `IDndResult` interface for drag-and-drop results.
- Created `IConfirmState` interface for confirmation state.
___ …

Integrate Confirmation Modal and Enhance Drag-and-Drop Logic in Kanban Board

---

src/components/sections/job-detail/TabMenuHorizontal.tsx

Bug fix
___
- Fixed the extraction of `jobId` from URL parameters in `TabMenuHorizontal` component to ensure correct navigation.
___
<tr>
<td>
<details>
<summary><strong>TabMenuHorizontal.tsx</strong><dd><code>Fix jobId extraction from URL parameters</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/sections/job-detail/TabMenuHorizontal.tsx
<li>Changed the destructuring of <code>useParams</code> to correctly extract <code>jobId</code>.<br>
</details>
</td>
<td><a href="https://github.com/UCTalent/uc-ats-react-app/pull/34/files#diff-7f474144520d99dc02 …

Fix jobId extraction from URL parameters in TabMenuHorizontal component

---

src/assets/icons/three-dots-horizontal.svg
src/components/common/JobCard.tsx
src/components/common/tags/NumberWithLabelVerticalTag.tsx
src/components/sections/TheAppHeader.tsx
src/components/sections/TheNavigateAsideBar.tsx
src/components/sections/home/TheJobsList.tsx
src/components/subsections/home/TabsFilter.tsx
src/constants/STYLE.ts
src/theme/createTheme.ts

Enhancement, Tests
___
- Added `onClickTitle` prop to `JobCard` component to make job titles clickable.
- Created new `NumberWithLabelVerticalTag` component for displaying labeled numbers.
- Added padding to `AppContainer` in `TheAppHeader`.
- Updated styles and constants in `TheNavigateAsideBar`.
- Refactored job list in `TheJobsList` and added `TabsFilter` component.
- Created `TabsFilter` component for status tabs with state management.
- Added `ASIDE_NAVIGATE_WIDTH` constant in `STYLE.ts`.
- Updated theme colors and added new variables in `createTheme.ts`.
___
<tr>
<td>
<details>
<summary><strong>JobCard.tsx</strong><dd><code>Add clickable job title …

Enhance UI/UX with new components and style updates

---

src/components/sections/TheNavigateAsideBarCollapseExpand.tsx
src/components/subsections/job-detail/DndTriggerScrollContainers.tsx
src/constants/STORAGE_KEY.ts
src/hooks/usePersistState.ts
src/layouts/app/header-with-asidebar/_HeaderWithAsideBarLayout.tsx
src/pages/TheJobCandidatePage.tsx

Enhancement, Bug fix
___
- Adjusted import order and improved navigation item styling in `TheNavigateAsideBar`.
- Added a new component `TheNavigateAsideBarCollapseExpand` for collapsible and expandable navigation aside bar.
- Created a custom hook `usePersistState` for persisting state in local storage.
- Replaced `TheNavigateAsideCollapseBar` with `TheNavigateAsideBarCollapseExpand` in the layout.
- Added `dndBoardElement` prop to `DndTriggerScrollContainers` and adjusted positioning.
- Added new storage key constant for navigation expansion state.
___
<tr>
<td>
<details>
<summary><strong>TheNavigateAsideBar.tsx</strong><dd><code>Adjust import order …

Enhance navigation aside bar with collapse/expand functionality and improve drag-and-drop container positioning

---

src/components/sections/AppHeader.tsx
src/components/sections/NavigateAsideBar.tsx
src/components/sections/NavigateAsideBarCollapseExpand.tsx
src/components/sections/TheNavigateAsideCollapseBar.tsx
src/components/subsections/job-detail/DndTriggerScrollContainers.tsx
src/layouts/_base.tsx
src/layouts/app/_app-header-with-aside-bar.tsx

enhancement
___
- Renamed several components by removing the 'The' prefix for consistency and clarity.
- Updated import and export statements across multiple files to reflect the new component names.
- Adjusted the `left` style property calculation in `DndTriggerScrollContainers.tsx` for better alignment.
___
<tr>
<td>
<details>
<summary><strong>AppHeader.tsx</strong><dd><code>Rename AppHeader component for consistency</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/sections/AppHeader.tsx
<li>Renamed component <code>TheAppHeader</code> to …

Refactor component naming for consistency and clarity

---

src/components/common/PopConfirm.tsx
src/components/common/TypographyHtml.tsx
src/hooks/atoms/useConfirmAtom.ts
src/hooks/useDndKanbanBoard.ts
src/services/dnd/getChangeStatusWarningMessage.ts
src/services/sanitizeHTML/sanitizeHTMLBasic.ts
src/types/store/confirm.ts

enhancement, bug fix
___
- Enhanced the `PopConfirm` component to support dynamic content rendering using a new `render` function.
- Introduced a utility function `getChangeStatusWarningMessage` for generating dynamic warning messages in the Kanban board.
- Updated HTML sanitization to allow `style` attributes for `p` and `span` tags.
- Extended the `IConfirmState` type to include a `render` function for more flexible content management.
___
<tr>
<td>
<details>
<summary><strong>PopConfirm.tsx</strong><dd><code>Enhance PopConfirm component with dynamic content rendering</code></dd></summary>
<hr>
src/components/common/PopConfirm.tsx
<li>Added …

Enhance PopConfirm component with dynamic content rendering and update HTML sanitization

---

.env.example
README.md
package.json
schema.graphql
src/App.tsx
src/components/common/LoadingSuspense.tsx
src/constants/env.ts
src/environment.ts
src/pages/TheHomePage.tsx
src/pages/__generated__/TheHomePageQuery.graphql.ts
tsconfig.app.json
tsconfig.json
tsconfig.node.json
vite.config.ts
yarn.lock

enhancement, documentation, configuration changes
___
- Integrated Relay GraphQL into the application, replacing Apollo with Relay Environment.
- Added a new `LoadingSuspense` component for managing loading states with `Suspense`.
- Updated Vite configuration to include `vite-plugin-relay`.
- Added GraphQL schema and environment configuration for Relay.
- Updated README with instructions for setting up and running Relay GraphQL.
- Adjusted TypeScript configurations to support Relay and updated dependencies.
___
</strong></td><td><details><summary>5 files</summary><table>
<tr>
<td>
<details>
<summary><strong>App.tsx</strong><dd><code>Integrate Relay Environment and Suspense in App …

Integrate Relay GraphQL and Update Project Configuration

---

src/hooks/mutations/useMutateGetProfileMe.ts
src/services/axios/axiosBasic.ts

Bug fix
___
- Fixed an issue causing infinite profile fetch by checking for the presence of an `access_token` cookie before making the request.
- Enhanced error handling by deleting the `access_token` cookie when a 401 error occurs, preventing unauthorized access loops.
- Improved window object check to ensure proper execution in browser environments.
___
<tr>
<td>
<details>
<summary><strong>useMutateGetProfileMe.ts</strong><dd><code>Fix infinite profile fetch by checking access token</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/hooks/mutations/useMutateGetProfileMe.ts
<li>Added import for <code>getCookie</code> utility.<br> <li> …

Fix infinite profile fetch and enhance 401 error handling

---

src/hooks/mutations/useMutateGetProfileMe.ts

Bug fix
___
- Fixed an issue causing infinite fetching of user profile when no access token is present by setting the fetch state to true.
- Ensured that the `setIsFetched` function is called to update the fetch status appropriately.
___
<tr>
<td>
<details>
<summary><strong>useMutateGetProfileMe.ts</strong><dd><code>Fix infinite fetching in user profile mutation</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/hooks/mutations/useMutateGetProfileMe.ts
<li>Added a call to <code>setIsFetched(true)</code> when no access token is found.<br> <li> Prevents infinite fetching by ensuring the fetch state is …

Fix infinite fetching issue in user profile mutation

---

src/pages/TheLoginPage.tsx

enhancement
___
- Enhanced the styling of the login page by adding `height: "100%"` to the `Box` component to ensure full height coverage.
- Improved the image display by setting `objectPosition: "center"` to better align the image within its container.
___
<tr>
<td>
<details>
<summary><strong>TheLoginPage.tsx</strong><dd><code>Enhance styling for login page components</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/pages/TheLoginPage.tsx
<li>Added <code>height: "100%"</code> to the <code>Box</code> component's style.<br> <li> Enhanced the <code>img</code> …

Enhance styling for TheLoginPage components

---

schema.graphql
src/components/sections/job-detail/TitleOverview.tsx
src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts
src/hooks/queries/useJobCandidatesQuery.ts
src/layouts/app/__job-detail-header.tsx
src/pages/TheJobCandidatePage.tsx
src/store/jobOverviewAtom.ts
src/types/store/job-overview.ts

enhancement, tests
___
- Enhanced the `TitleOverview` component to dynamically render job details using the `jobOverview` prop.
- Implemented a new `useJobCandidatesQuery` hook to fetch job candidates data using Relay and manage state with Recoil.
- Updated the job detail header layout to integrate and reset job overview state using Recoil.
- Extended the GraphQL schema to include additional job and talent-related fields and types.
- Added a Recoil atom for managing job overview state and defined a corresponding TypeScript interface.
___
<tr>
<td>
<details>
<summary><strong>TitleOverview.tsx</strong><dd><code>Enhance job overview rendering with dynamic …

Enhance job overview and implement job candidates query with state management

---

src/components/common/user-avatar/UserAvatarWithDetails.tsx
src/components/subsections/job-detail/CandidateStageColumnCard.tsx
src/hooks/queries/__generated__/useJobCandidateTalentSummaryQuery.graphql.ts
src/hooks/queries/useJobCandidateTalentSummaryQuery.ts
src/layouts/app/___job-detail-candidate-info.tsx
src/pages/TheHomePage.tsx
src/pages/job-candidate/TheJobCandidateSummaryPage.tsx
src/store/talentOverviewAtom.ts
src/types/store/talent-overview.ts

enhancement, tests
___
- Enhanced `UserAvatarWithDetails` component to render dynamic talent data using props.
- Implemented a custom hook `useJobCandidateTalentSummaryQuery` to fetch talent data with Relay and manage state using Recoil.
- Updated `CandidateStageColumnCard` to improve navigation logic.
- Integrated dynamic talent data fetching and rendering in `TheJobCandidateSummaryPage`.
- Added Recoil atom `talentOverviewAtom` for managing talent overview state.
- Removed unused imports from `TheHomePage`.
___
</strong></td><td><details><summary>7 files</summary><table>
<tr>
<td>
<details>
<summary><strong>UserAvatarWithDetails.tsx</strong><dd><code>Enhance …

Implement dynamic talent data fetching and rendering with GraphQL and Recoil

---

src/components/sections/job-detail/JobOverviewBox.tsx
src/constants/JOB.ts
src/pages/job-candidate/TheJobCandidateSummaryPage.tsx

enhancement
___
- Introduced constants `EXPERIENCE_LEVELS_NAME` and `MANAGEMENT_LEVELS_NAME` to map numeric levels to descriptive names.
- Updated `JobOverviewBox` component to use these mappings for displaying experience and management levels.
- Commented out the language section in `TheJobCandidateSummaryPage`.
___
<tr>
<td>
<details>
<summary><strong>JobOverviewBox.tsx</strong><dd><code>Map experience and management levels to descriptive names</code></dd></summary>
<hr>
src/components/sections/job-detail/JobOverviewBox.tsx
<li>Imported new constants for experience and management levels.<br> <li> Updated the display of experience and management levels …

Enhance job detail display with descriptive level mappings

---

src/layouts/app/_app-header-with-aside-bar.tsx

enhancement
___
- Enhanced the sidebar logic by replacing the `isJobDetailPath` check with an `isHomePath` check.
- Modified the conditional rendering to show `NavigateAsideBar` on the home path and `NavigateAsideBarCollapseExpand` otherwise.
___
<tr>
<td>
<details>
<summary><strong>_app-header-with-aside-bar.tsx</strong><dd><code>Update sidebar logic based on home path detection</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/layouts/app/_app-header-with-aside-bar.tsx
<li>Replaced <code>isJobDetailPath</code> logic with <code>isHomePath</code>.<br> <li> Updated conditional rendering of sidebar components.<br> …

Enhance sidebar logic with home path detection

---

src/App.tsx
src/components/sections/home/TheJobsList.tsx
src/components/sections/job-detail/CandidateStageColumn.tsx
src/constants/JOB.ts
src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts
src/hooks/queries/useJobCandidatesQuery.ts
src/hooks/useDndKanbanBoard.ts
src/pages/TheJobCandidatePage.tsx
src/services/api/job-apply.ts
src/services/job/candidates.ts
src/types/api/job-apply.ts

Enhancement, Bug fix
___
- Removed `Suspense` and `LoadingSuspense` from the `App` component to simplify the component structure.
- Updated `TheJobsList` component to use `locationValue` instead of `location` for the `city` prop, fixing a potential bug.
- Simplified the height calculation logic in `CandidateStageColumn` by removing unnecessary condition checks.
- Introduced `JOB_APPLY_STATUS` and `JOB_APPLY_STATUS_MAPPING` constants for better status management.
- Enhanced the `useJobCandidatesQuery` hook to support refetching and updated the GraphQL query to include additional fields.
- Added a `handleDrop` function to the `useDndKanbanBoard` hook to handle drop actions and update job application statuses.
- Implemented a new API service in `job-apply.ts` for updating job application …

Enhance job application status management and DnD functionality

---

schema.graphql
src/components/common/user-avatar/UserAvatarWithDetails.tsx
src/components/subsections/job-detail/CandidateStageColumnCard.tsx
src/hooks/queries/__generated__/useJobCandidateTalentSummaryQuery.graphql.ts
src/hooks/queries/useJobCandidateTalentSummaryQuery.ts
src/pages/TheJobCandidatePage.tsx

enhancement, bug fix
___
- Enhanced `CandidateStageColumnCard` component with `useCallback` and `useEffect` hooks, and integrated `useParams` and `useRecoilState` for better state management.
- Extended GraphQL query and schema to include `specialities` and `city` fields, allowing for more detailed data fetching.
- Updated `UserAvatarWithDetails` component to dynamically display the location using `talent?.place`.
- Refactored talent overview state management to exclude `status` and use `specialities` and `city` for `role` and `place`.
- Passed `status` prop to `CandidateStageColumnCard` in `TheJobCandidatePage`.
___
<tr>
<td>
<details> …

Enhance candidate components and extend GraphQL schema and queries

---

src/components/sections/AppHeader.tsx
src/hooks/mutations/useMutateGetProfileMe.ts
src/types/store/current-user.ts

enhancement
___
- Added the `avatar` property to the `UserAvatarWithChevron` component to display user profile photos.
- Enhanced the `useMutateGetProfileMe` hook to fetch and store the user's avatar URL.
- Updated the `ICurrentUserState` interface to include an `avatar` field for storing the user's profile picture URL.
___
<tr>
<td>
<details>
<summary><strong>AppHeader.tsx</strong><dd><code>Add avatar prop to UserAvatarWithChevron component</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/components/sections/AppHeader.tsx
- Added `avatar` prop to `UserAvatarWithChevron` component.
</details>
</td>
<td><a …

Add user profile photo functionality with avatar support

---

src/hooks/atoms/useCurrentUserAtom.ts

bug_fix
___
- Enhanced the `setLogoutUser` function to include clearing the `avatar` field in the user state.
- Implemented a redirect to the login page upon logout to improve user experience.
___
<tr>
<td>
<details>
<summary><strong>useCurrentUserAtom.ts</strong><dd><code>Enhance logout functionality by clearing user data and redirecting</code></dd></summary>
<hr>
src/hooks/atoms/useCurrentUserAtom.ts
<li>Added <code>avatar</code> field to <code>setCurrentUser</code> when logging out.<br> <li> Redirected user to login page on logout.<br>
</details>
</td>
<td><a href="https://github.com/UCTalent/uc-ats-react-app/pull/70/files#diff-2e1660ce7985891e77edf2ddcb2d …

Enhance logout process by clearing user data and redirecting to login

---

src/hooks/useDndKanbanBoard.ts
src/pages/TheJobCandidatePage.tsx
src/services/dnd/getChangeStatusWarningMessage.ts
src/utils/index.ts

enhancement, bug fix
___
- Enhanced the Kanban board hook to include an option for controlling card movement within the same column.
- Modified the job candidate page to prevent automatic refetching of job candidates and to disable inner column card movement.
- Fixed the status message in the drag-and-drop service to capitalize the first letter of the status.
- Introduced a new utility function to capitalize the first letter of a string.
___
<tr>
<td>
<details>
<summary><strong>useDndKanbanBoard.ts</strong><dd><code>Add options for inner column drop control in Kanban board</code></dd></summary>
<hr>
src/hooks/useDndKanbanBoard.ts
<li>Added …

Enhance Kanban board options and fix status message capitalization

---

src/App.tsx
src/components/sections/job-detail/TitleOverview.tsx
src/components/skeletons/JobTitleOverview.tsx
src/layouts/app/___job-detail-candidate-info.tsx
src/layouts/app/__job-detail-header.tsx

enhancement
___
- Enhanced UI/UX by integrating `Suspense` and `LoadingSuspense` components across various layouts and sections.
- Added skeleton loading components for job title overview to improve perceived performance during data fetching.
- Wrapped key components with `Suspense` to manage loading states effectively.
___
<tr>
<td>
<details>
<summary><strong>App.tsx</strong><dd><code>Integrate Suspense for Asynchronous Loading in App Component</code></dd></summary>
<hr>
src/App.tsx
<li>Added <code>Suspense</code> and <code>LoadingSuspense</code> for improved UI/UX.<br> <li> Wrapped components with <code>Suspense</code> for loading state management.<br> …

Enhance UI/UX with Suspense and Skeleton Loading Components

---

src/store/currentUserAtom.ts

enhancement
___
- Updated the default value of the `avatar` field in the `currentUserAtom` to an empty string.
- Reordered fields in the default state object, moving `userId` above `email` and `name`.
___
<tr>
<td>
<details>
<summary><strong>currentUserAtom.ts</strong><dd><code>Update default values in `currentUserAtom`</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/store/currentUserAtom.ts
<li>Updated the default value of the <code>avatar</code> field in the <code>currentUserAtom</code>.<br> <li> Moved the <code>userId</code> field to a different position in the …

Update default values for `currentUserAtom` in state management

---

schema.graphql
src/components/common/PdfViewer.tsx
src/components/sections/job-detail/job-candidate/TabMenuHorizontal.tsx
src/components/subsections/job-detail/CandidateStageColumnCard.tsx
src/constants/JOB.ts
src/hooks/queries/__generated__/useJobCandidateTalentResumeQuery.graphql.ts
src/hooks/queries/useJobCandidateTalentResumeQuery.ts
src/pages/job-candidate/TheJobCandidateResumePage.tsx
src/pages/job-candidate/TheJobCandidateSummaryPage.tsx

enhancement, tests
___
- Added a new `PdfViewer` component to display PDF documents using an iframe.
- Implemented a custom hook `useJobCandidateTalentResumeQuery` to fetch job candidate resume data.
- Created `TheJobCandidateResumePage` to display the candidate's resume using the `PdfViewer`.
- Updated GraphQL queries and hooks to fetch job application details instead of talent details.
- Enabled the "Resume" tab in the job candidate tab menu.
- Fixed candidate ID reference in `CandidateStageColumnCard`.
- Added `CANDIDATE_STATUS_NAME_MAPPING` for mapping candidate statuses to display names.
___
</strong></td><td><details><summary>8 files</summary><table>
<tr>
<td>
<details> …

Implement PDF Viewer and Fetch Job Candidate Resume Details

---

src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts

enhancement
___
- Updated the generated hash signature to reflect changes in the GraphQL query.
- Removed unnecessary fields from the GraphQL query to optimize performance.
- Renamed fields for improved clarity and consistency in the query.
- Adjusted the field selections to align with the updated query requirements.
___
<tr>
<td>
<details>
<summary><strong>useJobCandidatesQuery.graphql.ts</strong><dd><code>Update and optimize GraphQL query structure</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
src/hooks/queries/__generated__/useJobCandidatesQuery.graphql.ts
<li>Updated …

Optimize and Update GraphQL Query Structure in Generated File
